Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\learning_platform\settings.py changed, reloading.
Watching for file changes with StatReloader
Starting registration process
User artemkondm created successfully
Attempting to authenticate user artemkondm
User artemkondm authenticated successfully
User artemkondm logged in successfully
Watching for file changes with StatReloader
Starting registration process
User gggg created successfully
Attempting to authenticate user gggg
User gggg authenticated successfully
User gggg logged in successfully
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /accounts/profile/
Not Found: /accounts/profile/
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\users\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /accounts/profile/
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /courses/create/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py", line 50, in create_course
    return redirect('courses:course_detail', course_id=course.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\shortcuts.py", line 130, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course_detail' with keyword arguments '{'course_id': 1}' not found. 1 pattern(s) tried: ['courses/course/(?P<pk>[0-9]+)/\\Z']
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\users\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/course/1/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: courses_lesson.content

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\defaulttags.py", line 171, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: courses_lesson.content
Watching for file changes with StatReloader
Internal Server Error: /courses/1/create-lesson/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py", line 66, in create_lesson
    return redirect('courses:course_detail', course_id=course.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\shortcuts.py", line 130, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course_detail' with keyword arguments '{'course_id': 1}' not found. 1 pattern(s) tried: ['courses/course/(?P<pk>[0-9]+)/\\Z']
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\homepage\views.py", line 7, in homepage
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
Not Found: /accounts/login/
Internal Server Error: /courses/1/lesson/1/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py", line 101, in lesson_detail
    return render(request, 'courses/lesson_detail.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lesson_detail' with keyword arguments '{'course_id': 1, 'pk': 2}' not found. 1 pattern(s) tried: ['courses/(?P<course_id>[0-9]+)/lesson/(?P<lesson_id>[0-9]+)/\\Z']
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/1/lesson/3/delete/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: courses_test.lesson_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py", line 148, in delete_lesson
    lesson.delete()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\base.py", line 966, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\deletion.py", line 295, in collect
    if sub_objs:
       ^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\query.py", line 284, in __bool__
    self._fetch_all()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: courses_test.lesson_id_id
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/1/lesson/1/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: courses_lessonimage

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\courses\views.py", line 110, in lesson_detail
    return render(request, 'courses/lesson_detail.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\defaulttags.py", line 308, in render
    match = condition.eval(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\defaulttags.py", line 892, in eval
    return self.value.resolve(context, ignore_failures=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 671, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 796, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\template\base.py", line 858, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\query.py", line 808, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\sql\query.py", line 561, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1145, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\learning_platform-main\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: courses_lessonimage
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /courses/1/lesson/1/test/1/edit/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 237, in edit_test
    questions = Question.objects.filter(test=test)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'test' into field. Choices are: choicequestion, id, inputquestion, matchquestion, test_id, test_id_id, text, type
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /courses/courses/1/lessons/1/tests/1/take/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 400, in take_test
    return render(request, 'courses/take_test.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\defaulttags.py", line 171, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1326, in _fetch_all
    self._prefetch_related_objects()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 813, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1713, in prefetch_related_objects
    raise AttributeError("Cannot find '%s' on %s object, '%s' is an invalid "
AttributeError: Cannot find 'inputquestion' on Question object, 'inputquestion' is an invalid parameter to prefetch_related()
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/courses/1/lessons/1/tests/1/take/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: courses_choicequestion.question_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 400, in take_test
    return render(request, 'courses/take_test.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\defaulttags.py", line 171, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1326, in _fetch_all
    self._prefetch_related_objects()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 813, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1730, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(
                                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1855, in prefetch_one_level
    prefetcher.get_prefetch_queryset(instances, lookup.get_current_queryset(level)))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 637, in get_prefetch_queryset
    for rel_obj in queryset:
                   ^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 280, in __iter__
    self._fetch_all()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: courses_choicequestion.question_id
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\learning_platform\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\learning_platform\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/course/1/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: example.html
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/1/lesson/1/test/1/add-question/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: courses_inputquestion.question_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 331, in add_question
    input_question.save()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: courses_inputquestion.question_id_id
Internal Server Error: /courses/1/lesson/1/test/1/add-question/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: courses_inputquestion.question_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 331, in add_question
    input_question.save()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: courses_inputquestion.question_id_id
Internal Server Error: /courses/1/lesson/1/test/1/add-question/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: courses_inputquestion.question_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 331, in add_question
    input_question.save()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: courses_inputquestion.question_id_id
Internal Server Error: /courses/1/lesson/1/test/1/add-question/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: courses_inputquestion.question_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 331, in add_question
    input_question.save()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: courses_inputquestion.question_id_id
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /courses/1/lesson/1/test/1/add-question/undefined
Not Found: /courses/1/lesson/1/test/1/add-question/undefined
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/1/lesson/1/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 168, in lesson_detail
    return render(request, 'courses/lesson_detail.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 260: 'endif', expected 'endblock'. Did you forget to register or load this tag?
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/3/lesson/19/test/3/add-question/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 392, in add_question
    ChoiceQuestion.objects.create(
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 451, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 503, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: ChoiceQuestion() got an unexpected keyword argument 'question'
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/3/lesson/19/test/3/add-question/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: courses_question.test_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 325, in add_question
    question.save()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: courses_question.test_id_id
Internal Server Error: /courses/3/lesson/19/test/3/add-question/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: courses_question.test_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 325, in add_question
    question.save()
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: courses_question.test_id_id
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/3/lesson/19/test/3/add-question/
Internal Server Error: /courses/3/lesson/19/test/3/add-question/
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /courses/3/lesson/19/test/3/add-question/
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/courses/3/lessons/19/tests/3/take/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: courses_testresult.user_id, courses_testresult.test_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 492, in take_test
    TestResult.objects.create(
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: courses_testresult.user_id, courses_testresult.test_id
Internal Server Error: /courses/courses/3/lessons/19/tests/3/take/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: courses_testresult.user_id, courses_testresult.test_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py", line 492, in take_test
    TestResult.objects.create(
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: courses_testresult.user_id, courses_testresult.test_id
Watching for file changes with StatReloader
Not Found: /favicon.ico
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
Not Found: /accounts/login/
Not Found: /accounts/login/
Not Found: /accounts/login/
Not Found: /accounts/login/
Starting registration process
User teacher created successfully
Attempting to authenticate user teacher
User teacher authenticated successfully
User teacher logged in successfully
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
Starting registration process
User student created successfully
Attempting to authenticate user student
User student authenticated successfully
User student logged in successfully
Watching for file changes with StatReloader
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\learning_platform\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\learning_platform\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\learning_platform\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\learning_platform\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\learning_platform\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\learning_platform\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\learning_platform\urls.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
Watching for file changes with StatReloader
Method Not Allowed (GET): /users/logout/
Method Not Allowed: /users/logout/
Internal Server Error: /courses/
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'logout' not found. 'logout' is not a valid view function or pattern name.
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\learning_platform\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /tests/3
Internal Server Error: /courses/tests/3/
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: test_list.html, courses/testresult_list.html
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/tests/3/
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: test_list.html, courses/testresult_list.html
Internal Server Error: /courses/tests/3/
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: test_list.html, courses/testresult_list.html
Watching for file changes with StatReloader
Internal Server Error: /courses/tests/3/
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: test_list.html, courses/testresult_list.html
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /courses/tests/3/
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py", line 24, in get_queryset
    print(TestResult.objects.filter(teacher=teacher.id, test_id=test_id))
                                            ^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'id'
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/tests/3/
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py", line 24, in get_queryset
    print(TestResult.objects.filter(teacher=teacher, test_id=test_id))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'teacher' into field. Choices are: completed_at, id, score, test, test_id, user, user_id
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/tests/3/
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py", line 22, in get_queryset
    teacher_id = get_user_model().objects.filter(username=self.request.user).id
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'id'
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /courses/tests/3/
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py", line 24, in get_queryset
    print(TestResult.objects.filter(teacher=teacher_id, test_id=test_id))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'teacher' into field. Choices are: completed_at, id, score, test, test_id, user, user_id
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Admin\Documents\Python\KFU\Multimedia_technologies\practice1\learning_platform\courses\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /courses/tests/3/
Traceback (most recent call last):
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\venv\Lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lesson_detail' with keyword arguments '{'course_id': '', 'lesson_id': ''}' not found. 1 pattern(s) tried: ['courses/(?P<course_id>[0-9]+)/lesson/(?P<lesson_id>[0-9]+)/\\Z']
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\xdin4\OneDrive\Рабочий стол\dsadas\learning_platform\courses\views.py changed, reloading.
Watching for file changes with StatReloader
